version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: namesdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_init:/docker-entrypoint-initdb.d/ 
    networks:
      - appnet
    deploy:
      placement:
        constraints:
          - node.labels.role == db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d namesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: chhuang007/backend:latest
    environment:
      DB_HOST: db
      DB_NAME: namesdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == backend

  frontend:
    image: chhuang007/frontend:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == frontend

networks:
  appnet:
    driver: overlay

volumes:
  db_data:
    driver: local